---
- block:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://apt.vector.dev/pool/v/ve/vector_{{ vector_version }}-1_{{ arch }}.deb"
        dest: "./vector_{{ vector_version }}-1_{{ arch }}.deb"

- name: Install vector packages
  ansible.builtin.apt:
    deb: vector_{{ vector_version }}-1_{{ arch }}.deb
    update_cache: yes
    #upgrade: yes
  notify: Start vector service

- name: Template a file to /etc/vector/config.toml
  ansible.builtin.template:
    src: ./roles/vector/tamplates/config.j2
    dest: /etc/vector/config.toml
    mode: '0644'


